### ISSUE TITLE
Angular module non working with jquery UI 1.10.4

### ISSUE THREAD

**Issue by chatellier** [blueimp/jQuery-File-Upload#2904]
Since jquery 1.10.4 update, angular module is not working anymore:
Uncaught TypeError: Property 'scope' of object #<Object> is not a function 

On line L89: https://github.com/blueimp/jQuery-File-Upload/blob/master/js/jquery.fileupload-angular.js#L89,
var scope = data.scope(), fails now.

In jquery 1.10.3, it's a function
In jquery 1.10.4, it's an array
